### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Bananaman**
After talking to the mujs author, we were able to upstream the arch patches.

This pull requests updates mujs to v1.1.0, removes the old patch file, and updates all other outdated dependencies (waf, ffmpeg and youtube-dl). Everything is now up to date again.

We do gain some new default "release" mujs build flags that we didn't have before, but they are harmless since they just relate to optimization and removing debug symbols for size:

- Builds with "-Os" (optimize for size).
- Links with "-s" (removes symbol table from executable).

Celluloid has been tested with all these updates and is working.

### CODE REVIEW

**Comment by Bananaman** [comment]
cc @TingPing

**Comment by Bananaman** [comment]
By the way @TingPing, does flathub automatically update to the latest commits in this repo, or is that manual? (I am curious not just for this project).

https://flathub.org/apps/details/io.github.celluloid_player.Celluloid is still on the February 2nd commits.

**Comment by TingPing** [comment]
Each commit is built and deployed with a small delay, see https://flathub.org/builds

The website has it's own delay which I don't know of but the app can be more up to date.

**Comment by Bananaman** [comment]
@TingPing Ahh, thank you very much for explaining that. Great to know how it works. 😃 👍

**Pull request merged**
